In [ ]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [ ]:
print(torch.__version__)

2.1.0+cu121


Creating a tensor, we have different types:
-scalar
-vector

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() #get tensor back as python int

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim  #dimension is the number of opened squared brackets

1

In [ ]:
vector.shape #it's 2 since we have 2 numbers

torch.Size([2])

In [ ]:
#MATRIX
MATRIX= torch.tensor([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim #it's 2 since we have two opening squared brackets

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape  #it's a 2x, 2 element inside [] and 2 []

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3,6,9], [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim


3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
tensor = torch.tensor([[[[0, 1, 2], [3, 4, 5], [6, 7, 8],[9, 10, 11]]]])
tensor

tensor([[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8],
          [ 9, 10, 11]]]])

In [ ]:
tensor.ndim

4

In [ ]:
tensor.shape

torch.Size([1, 1, 4, 3])

2°CHAPTER: RANDOM TENSORS

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update ranodm numbers -> look at data -> update ranodm numbers

In [ ]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,2,4,5)
#last number-> columns
#last-1 number -> rows
#last-2 number -> how many of 4x5 are in each repetation
#first number -> how many times it's repeated
random_tensor

tensor([[[[0.3497, 0.2184, 0.0035, 0.8218, 0.2511],
          [0.7832, 0.9002, 0.0756, 0.1413, 0.9218],
          [0.4697, 0.3969, 0.4969, 0.0980, 0.3580],
          [0.5214, 0.9984, 0.4333, 0.8006, 0.9160]],

         [[0.2647, 0.4348, 0.9375, 0.5905, 0.5862],
          [0.6316, 0.5183, 0.6828, 0.6180, 0.7570],
          [0.3520, 0.0359, 0.2644, 0.9810, 0.3912],
          [0.3683, 0.5714, 0.5729, 0.9411, 0.0041]]],


        [[[0.6513, 0.9825, 0.4202, 0.0895, 0.7719],
          [0.4712, 0.7493, 0.5089, 0.9901, 0.7092],
          [0.5624, 0.4390, 0.9617, 0.2032, 0.1761],
          [0.2713, 0.1979, 0.7947, 0.0353, 0.2505]],

         [[0.6864, 0.4598, 0.9891, 0.3325, 0.5873],
          [0.8459, 0.7931, 0.5490, 0.5769, 0.8209],
          [0.2567, 0.7502, 0.2996, 0.5990, 0.3983],
          [0.2002, 0.2494, 0.5857, 0.0669, 0.9699]]],


        [[[0.4186, 0.3355, 0.0790, 0.3913, 0.6935],
          [0.7012, 0.9825, 0.8931, 0.9774, 0.0020],
          [0.3098, 0.7135, 0.1801, 0.7066, 0.4011],


In [ ]:
random_tensor.ndim

4

In [ ]:
random_tensor.shape

torch.Size([3, 2, 4, 5])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #colour channel (R,G,B), heigh, width
random_image_size_tensor.shape, random_image_size_tensor.ndim
random_image_size_tensor

tensor([[[0.6913, 0.9722, 0.8581],
         [0.1170, 0.2766, 0.8606],
         [0.9450, 0.7159, 0.7192],
         ...,
         [0.8115, 0.5609, 0.5215],
         [0.1361, 0.5846, 0.4021],
         [0.9309, 0.3650, 0.4343]],

        [[0.6777, 0.7310, 0.4367],
         [0.7582, 0.4337, 0.1615],
         [0.2338, 0.7271, 0.8784],
         ...,
         [0.1002, 0.0704, 0.3323],
         [0.1540, 0.2017, 0.7933],
         [0.7292, 0.6562, 0.5889]],

        [[0.7028, 0.2427, 0.7451],
         [0.7475, 0.4202, 0.0446],
         [0.5513, 0.7619, 0.2637],
         ...,
         [0.7550, 0.5311, 0.4543],
         [0.1940, 0.6749, 0.2622],
         [0.0231, 0.7299, 0.7157]],

        ...,

        [[0.6065, 0.4504, 0.8327],
         [0.8242, 0.5507, 0.2282],
         [0.8523, 0.7133, 0.7431],
         ...,
         [0.7932, 0.1193, 0.5621],
         [0.3971, 0.2856, 0.9117],
         [0.8429, 0.5372, 0.9897]],

        [[0.5575, 0.7575, 0.2759],
         [0.8391, 0.0716, 0.2860],
         [0.

In [ ]:
a=torch.tensor([[7,3,4,8], [6,7,3,4]])
a

tensor([[7, 3, 4, 8],
        [6, 7, 3, 4]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

torch.Size([2, 4])

In [ ]:
image=torch.rand(size=(3,224,224))
image

tensor([[[0.4225, 0.5040, 0.3510,  ..., 0.1940, 0.7883, 0.7263],
         [0.2596, 0.6301, 0.4709,  ..., 0.1068, 0.0521, 0.3144],
         [0.2411, 0.7681, 0.7194,  ..., 0.7729, 0.4216, 0.1912],
         ...,
         [0.7627, 0.9667, 0.3773,  ..., 0.3411, 0.3139, 0.6344],
         [0.7842, 0.8826, 0.3788,  ..., 0.3784, 0.9200, 0.6333],
         [0.5584, 0.7852, 0.3590,  ..., 0.5965, 0.3983, 0.9416]],

        [[0.6228, 0.1966, 0.2509,  ..., 0.3513, 0.0890, 0.1685],
         [0.1928, 0.3292, 0.2657,  ..., 0.5036, 0.9333, 0.9381],
         [0.3274, 0.1621, 0.8793,  ..., 0.4926, 0.8137, 0.5603],
         ...,
         [0.4490, 0.1695, 0.5406,  ..., 0.8036, 0.8778, 0.2845],
         [0.9176, 0.6711, 0.3177,  ..., 0.6955, 0.1123, 0.5417],
         [0.8389, 0.6716, 0.6706,  ..., 0.7118, 0.5960, 0.3561]],

        [[0.6912, 0.7943, 0.5118,  ..., 0.7023, 0.7397, 0.9063],
         [0.7521, 0.4244, 0.3919,  ..., 0.0840, 0.1017, 0.3041],
         [0.6550, 0.4314, 0.4704,  ..., 0.9612, 0.5307, 0.

In [ ]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
 torch.ones(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a=torch.range(1,10,2)

<ipython-input-27-82d1ee44cc4b>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a=torch.range(1,10,2)


In [ ]:
b=torch.ones_like(a)
b

tensor([1., 1., 1., 1., 1.])

In [ ]:
tensor16=torch.tensor([3,4,5], dtype=torch.float16)
tensor16

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
tensor32=tensor16.type(torch.float32)
tensor32

tensor([3., 4., 5.])

In [ ]:
 a=torch.rand(4,5)
 a

tensor([[0.3969, 0.0570, 0.0898, 0.0413, 0.2710],
        [0.7636, 0.3169, 0.3325, 0.7762, 0.9659],
        [0.1755, 0.4683, 0.8556, 0.2126, 0.2355],
        [0.5421, 0.1670, 0.6325, 0.6813, 0.8209]])

In [ ]:
a.shape

torch.Size([4, 5])

In [ ]:
a.dtype

torch.float32

In [ ]:
a.device

device(type='cpu')

In [ ]:
tensor=torch.tensor([1,2,3])
tensor += 10
tensor

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor,2)

tensor([22, 24, 26])

In [ ]:
a=torch.tensor([1,2,3])
b=torch.tensor([1,2,3])
torch.matmul(a,b)

tensor(14)

In [ ]:
#shapes for matrix multiplications
tensor1=torch.tensor([[1,2],[3,4],[5,6]])
tensor2= torch.tensor([[7,10], [8,11],[9,12]])
torch.mm(tensor1,tensor2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor1.shape, tensor2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor2.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.matmul(tensor1,tensor2.T).shape

torch.Size([3, 3])

In [ ]:
x=torch.arange(0,100,10)

In [ ]:
torch.min(x)

tensor(0)

In [ ]:
x.max(),x.min()

(tensor(90), tensor(0))

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
import torch

In [ ]:
x= torch.arange(1.0,10.0)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_resh = x.reshape(1,9)
x_resh, x_resh.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x.view(1,9)

In [ ]:
x_resh.squeeze().shape

torch.Size([9])

In [ ]:
a = torch.rand(3,4,2)
a, a.shape

(tensor([[[0.8173, 0.6839],
          [0.6588, 0.4451],
          [0.2655, 0.3281],
          [0.4217, 0.8825]],
 
         [[0.6528, 0.6186],
          [0.8871, 0.6827],
          [0.8698, 0.9569],
          [0.2691, 0.5860]],
 
         [[0.5895, 0.9066],
          [0.9911, 0.8915],
          [0.0435, 0.1511],
          [0.4587, 0.6363]]]),
 torch.Size([3, 4, 2]))

In [ ]:
torch.permute(a, (1,0,2)).shape

torch.Size([4, 3, 2])

In [ ]:
print( "Previous dimension: {x_resh}")


In [ ]:
tensor = torch.rand(4,3,2,3)
tensor, tensor.shape

(tensor([[[[0.6459, 0.8222, 0.7340],
           [0.5706, 0.9599, 0.0376]],
 
          [[0.8262, 0.1816, 0.0182],
           [0.0571, 0.7755, 0.0628]],
 
          [[0.6937, 0.5745, 0.1940],
           [0.1585, 0.8586, 0.6145]]],
 
 
         [[[0.0576, 0.1647, 0.9693],
           [0.9900, 0.6324, 0.0287]],
 
          [[0.8323, 0.5017, 0.7945],
           [0.6131, 0.6186, 0.9343]],
 
          [[0.7460, 0.1978, 0.9573],
           [0.7735, 0.1279, 0.2751]]],
 
 
         [[[0.8427, 0.4856, 0.3723],
           [0.7389, 0.5324, 0.3345]],
 
          [[0.7018, 0.6031, 0.1851],
           [0.1806, 0.8732, 0.6340]],
 
          [[0.5269, 0.8659, 0.9396],
           [0.9967, 0.7893, 0.0047]]],
 
 
         [[[0.0848, 0.1295, 0.6897],
           [0.7151, 0.6157, 0.9807]],
 
          [[0.0433, 0.9653, 0.1653],
           [0.0481, 0.8059, 0.6490]],
 
          [[0.6622, 0.4234, 0.9087],
           [0.5455, 0.2783, 0.1718]]]]),
 torch.Size([4, 3, 2, 3]))

In [ ]:
tensor[0][0]

tensor([[0.6459, 0.8222, 0.7340],
        [0.5706, 0.9599, 0.0376]])

In [ ]:
a = torch.arange(1,10).reshape(1,3,3)
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
a[0][2][2]

tensor(9)

In [ ]:
a[:,:,2]

tensor([[3, 6, 9]])

# **Exercises**

In [ ]:
import torch



In [ ]:
rand_tensor=torch.rand(7,7)
rand_tensor.shape

torch.Size([7, 7])

In [ ]:
tensor2 = torch.rand(1,7)
tensor2.shape

torch.Size([1, 7])

In [ ]:
inverse_2 = tensor2.T

matrix=torch.matmul(rand_tensor,inverse_2)

matrix

tensor([[0.6971],
        [0.9420],
        [1.0426],
        [2.0437],
        [1.6560],
        [1.0629],
        [1.4949]])

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random1 = torch.rand(7,7)
random2 = torch.rand(1,7)
random2_inv = random2.T
matrix2 = torch.matmul(random1, random2_inv)
matrix

tensor([[0.6971],
        [0.9420],
        [1.0426],
        [2.0437],
        [1.6560],
        [1.0629],
        [1.4949]])

In [ ]:
torch.max(matrix), torch.min(matrix)

(tensor(2.3630), tensor(0.9162))

In [ ]:
torch.argmin(matrix), torch.argmax(matrix)

(tensor(3), tensor(1))

In [ ]:
a=torch.rand(1,1,1,10)
a_squeezed=a.squeeze()
a_squeezed, a_squeezed.shape

(tensor([0.5995, 0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012, 0.5936,
         0.4158]),
 torch.Size([10]))